version: "3.1"
services:

    node:
      build: node
      image: node:8-slim
      container_name: "node-api"
      command: npm run start
      working_dir: /app
      volumes:
        - ./node/api:/app
      depends_on:
        - mongo
      environment:
        - NODE_ENV=development
      links:
        - mongo
      ports:
        - "3000:3000"

    mongo:
        image: mongo:latest
        container_name: "mongo"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/
          - MONGODB_USER="user"
          - MONGODB_PASS="pass"
        volumes:
          - ./persistent-data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
